// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH2IKaylE2RzedtuJA7N9tvA43vVCdthg',
    appId: '1:628671487742:web:c9e3a508c184951f22cfaf',
    messagingSenderId: '628671487742',
    projectId: 'exemplo-92aed',
    authDomain: 'exemplo-92aed.firebaseapp.com',
    storageBucket: 'exemplo-92aed.appspot.com',
    measurementId: 'G-9CC2R8SSVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2GNKpJRu-Q31a4MLIK3lnx6HJImiRoM',
    appId: '1:628671487742:android:58746a2f96732cc822cfaf',
    messagingSenderId: '628671487742',
    projectId: 'exemplo-92aed',
    storageBucket: 'exemplo-92aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Lur6gsDhTvmPE-NDkoEzstKvDMH94jQ',
    appId: '1:628671487742:ios:99040555b6b4800a22cfaf',
    messagingSenderId: '628671487742',
    projectId: 'exemplo-92aed',
    storageBucket: 'exemplo-92aed.appspot.com',
    iosClientId: '628671487742-5outnlhcngee4hgtnbeamodh82duh800.apps.googleusercontent.com',
    iosBundleId: 'com.minimal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Lur6gsDhTvmPE-NDkoEzstKvDMH94jQ',
    appId: '1:628671487742:ios:99040555b6b4800a22cfaf',
    messagingSenderId: '628671487742',
    projectId: 'exemplo-92aed',
    storageBucket: 'exemplo-92aed.appspot.com',
    iosClientId: '628671487742-5outnlhcngee4hgtnbeamodh82duh800.apps.googleusercontent.com',
    iosBundleId: 'com.minimal',
  );
}
